### ISSUE TITLE
Problem with Xiaomi Smart Standing Fan 2 Lite.

### ISSUE THREAD

**Issue by sirector20** [ikaruswill/lovelace-fan-xiaomi#117]
I have a problem with Xiaomi Smart Standing Fan 2 Lite, can't adjust the speed. and adjust the rotation angle What do I have to do?

**Comment by TSA3000** [comment]
Same problem here, i don't know how to edit the card

**Comment by Gideon-ZA** [comment]
Hi,
Has anyone fixed the issue? I can only change the speed from 2 to 4 on my Xiaomi Smart Standing Fan 2 Lite.

**Comment by insajd** [comment]
Probably this fan (dmaker.fan.1c) needs same change as zhimi.fan.fa1 as that fan also supports only 3 levels.

```
xiaomi-fan-card.ts

      //temp solution for FA1 fan until proper fan support is added in the upstream
      if (["zhimi.fan.fa1"].includes(attrs["model"])) {
```

**Comment by LuisDiazUgena** [comment]
where do we need to add this @insajd ??

**Comment by insajd** [comment]
@LuisDiazUgena please test changes.
[xiaomi-fan-card.zip](https://github.com/ikaruswill/lovelace-fan-xiaomi/files/11905923/xiaomi-fan-card.zip)

1. Navigate to the **/config/www/community/lovelace-fan-xiaomi** directory. Inside this directory, you will find several .js and .js.gz files.
2. Delete all of these **.js** and **.js.gz** files.
3. In the same directory, upload the **.js** files that are included in the attached archive to this message.
4. Once you have replaced the files, please refresh your browser. While doing this, ensure that your browser isn't using cached data. You can typically achieve this by pressing **Ctrl + R**.

By following these steps, you should be able to successfully replace the necessary files. If you have any issues, don't hesitate to ask for further assistance.

**Comment by insajd** [comment]
![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/1233490/556e35a8-9e34-41e9-8992-f2536c31f1ca)
This is how it looks prior to changes - files that I currently have in the folder. In ZIP there are only .js files.
Let me know if it fixes this issue.

**Comment by LuisDiazUgena** [comment]
Hi @insajd, I have replaced the files with the ones that you attached (thanks by the way) and the fan speed controller now works fine - in moves through the states properly.

What I don't like from this interface is that you don't know which speed is currently been used and there is no oscillation or natural mode toggle.

**Comment by insajd** [comment]
@LuisDiazUgena  was oscillation and natural toggle mode there before? if yes, then this new ZIP should bring them back. if not - please send **attributes** list of the fan entity with values.
"which speed is currently been used" - doesn't it show current speed? can you attach screenshot of the card please
[xiaomi-fan-card.zip](https://github.com/ikaruswill/lovelace-fan-xiaomi/files/11915669/xiaomi-fan-card.zip)

**Comment by LuisDiazUgena** [comment]
Hi!

This is with the version from hacs:

![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/6543254/80187111-b64b-45ac-aac2-7c346dbae1e9)

There are three thing that does not work here:

1. Fan movement right and left from the fan animated image
2. Angle toggle
3. Speed bumps from 0 to 2 to 4.

Everything else works.

This is with the zip from your last message @insajd: 

![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/6543254/79375d27-fa0c-43db-b640-c4907a658c04)

Everything works, except:

1. Fan movement right and left from the fan animated image
2. Angle toggle

I have reuploaded the zip from https://github.com/ikaruswill/lovelace-fan-xiaomi/issues/117#issuecomment-1613156014 and this is how it looks:

![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/6543254/c7aade73-6941-40eb-b640-7602521946be)

In both cases I have reloaded with chrome inspector tool opened and reload without cache option enable:

![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/6543254/2a3cb978-ec88-40ac-97b9-50e5d9dc74dc)

Please notice that in previous zipped folder there are 6 files. In the newest one there are only 3. Might this be the root cause of the card mismatch?
old:
![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/6543254/58dd5f9a-84bd-49e1-9120-05dc494b517e)
new:
![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/6543254/33deaedd-7d1e-4225-892d-6b6e66903985)

**Comment by insajd** [comment]
The build command creates 3 files for me, so it must be that just 3 are needed. Other files were in previous ZIP were probably some old versions that accidently got included.

Can you send attribute list of your fan ? [developer-tools/state ](http://ha:8123/developer-tools/state)

**Comment by insajd** [comment]
@LuisDiazUgena also, your fan does support angle and movement from xiaomi app, yes?

**Comment by LuisDiazUgena** [comment]
preset_modes: off, Level 1, Level 2, Level 3
oscillating: true
percentage: 33
percentage_step: 33.333333333333336
preset_mode: null
model: dmaker.fan.1c
angle: null
raw_speed: 1
delay_off_countdown: 0
ac_power: null
oscillate: true
direct_speed: null
natural_speed: null
child_lock: false
buzzer: false
led_brightness: null
use_time: null
temperature: null
humidity: null
battery: null
battery_charge: null
button_pressed: null
led: true battery_state:
null mode: normal
friendly_name: Xiaomi Fan
supported_features: 11

The fan does not support those modes from the app. Sorry for that, what I was trying to say is that does not work, hence it might be hiden for this model?

**Comment by insajd** [comment]
@LuisDiazUgena got you. In that case this should be what you need: 
[xiaomi-fan-card-9e34c58c.zip](https://github.com/ikaruswill/lovelace-fan-xiaomi/files/11917474/xiaomi-fan-card-9e34c58c.zip)
Let me know how it goes, I'll create a PR for this so that you could just use version from HACS.

**Comment by LuisDiazUgena** [comment]
that is great!

![image](https://github.com/ikaruswill/lovelace-fan-xiaomi/assets/6543254/eca113c6-23e2-4c24-a8d8-e7ad32f8f67f)

The only thing I'm missing from the xiaomi app in the card is the led indicator. it would be possible to add it?

Now looks superb anyways. thank you so much @insajd

**Comment by insajd** [comment]
@LuisDiazUgena you're welcome! Thanks for quick testing of builds 😉 Led is in your attributes with true value, so it can be added in theory. Let's create a new ticket for that change request.

**Comment by Sygnus83** [comment]
> @LuisDiazUgena got you. In that case this should be what you need: [xiaomi-fan-card-9e34c58c.zip](https://github.com/ikaruswill/lovelace-fan-xiaomi/files/11917474/xiaomi-fan-card-9e34c58c.zip) Let me know how it goes, I'll create a PR for this so that you could just use version from HACS.

Hello!

Should this be used for the 2 lite fan?
I deleted everything from the folder, copied these 3 js files.

Everything works fine except the speed.
For me, it is still 0-2-4 and not 0-1-2-3 .

**Comment by Zeronozero** [comment]
Is it planed any update for the speed problem ? (missing speed 1 and 3). Also for me the natural speed is not running.
