### ISSUE TITLE
Fan Speed issue with zhimi.fan.za5

### ISSUE THREAD

**Issue by Spegeli** [ikaruswill/lovelace-fan-xiaomi#61]
I own the Pedelstan Fan 3 and got a issue with the Fan Speed:

model: zhimi.fan.za5
integration: xiaomi_miio_fan

The Error:
"Fehler beim Aufrufen des Diensts fan/set_speed. The speed Level 4 is not a valid speed."

So Speed 3 is the Limit and because of this Error i can not switch back to Speed 1.

Thats the Attributes:

speed_list:
  - 'off'
  - low
  - medium
  - high
  - 'off'
  - Level 1
  - Level 2
  - Level 3
preset_modes:
  - 'off'
  - Level 1
  - Level 2
  - Level 3
oscillating: false
speed: Level 3
percentage: 100
percentage_step: 33.333333333333336
preset_mode: Level 3
model: zhimi.fan.za5

**Comment by ikaruswill** [comment]
I just upgraded my fan to the za5, and I'm seeing the same issue. It seems the issue stems from xiaomi_miio_fan integration, where the za5 is only recently added and do not yet have stable features.

In the entity attributes, Level 4 is also missing from the speed list

```
speed_list:
  - 'off'
  - low
  - medium
  - high
  - 'off'
  - Level 1
  - Level 2
  - Level 3
 ```

**Comment by insajd** [comment]
We can quickly allow iteration through 3 speeds instead of 4. Or option "use_standard_speeds: true"  can be used, then it will iterate through low/medium/high options.
I have made a 3 speed fix in branch https://github.com/ikaruswill/lovelace-fan-xiaomi/tree/insajd-za5_fan
@ikaruswill should we release 3 speed fix as 1.5.7-beta for za5 or wait for upstream fix?

**Comment by ikaruswill** [comment]
Oh wow you're fast. @insajd let's release a beta, while I'll look into how I can solve that with a PR upstream.

To confirm it's a toggle-able option right?

**Comment by insajd** [comment]
> Oh wow you're fast. @insajd thanks for your quick work as always. Let's release a beta, while I'll look into how I can solve that with a PR upstream.
> 
> To confirm it's a toggle-able option right?

* use_standard_speeds is togge-able option, it's present in 1.5.6 already and we don't need to release beta to use low/mid/high speeds. I suppose thiw will have something like 33,66,100% speeds.
* Speed 3 fix in branch is not togge-able. It's internal setup for za5 only, that makes za5 to support only 3 speeds. It will iterate back to 1 after speed 3. This will probably have 1,33,66% speeds.

First option can be used already, for second option we can release beta, which will influence only za5 fan. I'll go with it

**Comment by ikaruswill** [comment]
Roger that. let's roll with that fix for za5 temporarily until support is added.

I just poked upstream's upstream. Looks like the issue has been open for a while. ZA5 is using the new miotspec which is a whole new bag of worms and needs significant work. Likely we won't expect the fix to be here within the next month or so.

https://github.com/rytilahti/python-miio/issues/788

**Comment by ikaruswill** [comment]
@Spegeli Just so you know, there are some ongoing issues with upstream:
- Unable to send a turn left/turn right command to the fan
- Oscillation angle does not report nor set correctly
-

**Comment by ikaruswill** [comment]
@insajd It's working as expected, just tested with the ZA5. I'm able to cycle through all 3 speeds.

There are some weirdness that I observed however, due to the fan being not fully supported by `xiaomi_miio` yet.
- Speeds cycle through 1%, 35%, 74% instead of 1%, 33%, 66%
- `use_standard_speeds` will not work as `raw_speed` reports incorrect values.

For example, when speed is at `high`, or 74% (Read through Mi Home app):
```
raw_speed: 3
``` 

It appears that the `raw_speed` as of the current implementation, is reporting the speed level instead, and there's no attribute that reports the percentage speed correctly.

Nonetheless, I don't think we can or should implement any further hacks for ZA5. Thanks again!

**Comment by ikaruswill** [comment]
@Spegeli Do update to `1.5.7-beta2` should work as expected after a full, uncached refresh.

**Comment by Spegeli** [comment]
Works thx ;-)

Now its time to wait until the Miio Fan Adapter Dev adds the rest of the fan futures ^^

**Comment by insajd** [comment]
@ikaruswill you can try getting [this version,](https://github.com/rytilahti/python-miio/pull/1087) which ought to add support for the fan. https://github.com/rytilahti/python-miio/pull/1087 and get ready the support of the fan card.

**Comment by ikaruswill** [comment]
Nice spot. Will check that out.

**Comment by tieppm** [comment]
@ikaruswill  @insajd 
please fit for zhimi.fan.za5
no change in speed and natural mode
thank you

**Comment by ikaruswill** [comment]
Closing as za5 is now supported with native integration on 2.0.0
